services:
  calendar:
    build:
      context: .
      dockerfile: src/Infocal.Calendar/Dockerfile
    container_name: infocal-calendar

  scraper:
    build:
      context: .
      dockerfile: src/Infocal.Scraper/Dockerfile
    container_name: infocal-scraper

  admin:
    build:
      context: .
      dockerfile: src/Infocal.Admin/Dockerfile
    container_name: infocal-admin
