services:
  calendar:
    env_file:
      - .secret
    restart: unless-stopped
    ports:
      - "5253:80"
    volumes:
      - calendar-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Europe/Minsk

  scraper:
    env_file:
      - .secret
    restart: unless-stopped
    volumes:
      - scraper-data:/app/data
    environment:
      - DOTNET_ENVIRONMENT=Production
      - CalendarApi__BaseUrl=http://calendar
      - TZ=Europe/Minsk
    depends_on:
      - calendar

  admin:
    env_file:
      - .secret
    restart: unless-stopped
    ports:
      - "5254:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CalendarApi__BaseUrl=http://calendar
      - TZ=Europe/Minsk
    depends_on:
      - calendar

volumes:
  calendar-data:
  scraper-data:
